### ISSUE TITLE
Page not clickable - Extra HTML tags

### ISSUE THREAD

**Issue by mubarakone** [ethereum-boilerplate/ethereum-boilerplate#126] opened 2022-02-24 04:46 UTC
After `npm start` the folder after installing it, the page opens in a `localhost:3000`, however the page isn't interactable or clickable anywhere.

I suspect the problem is an extra `<html></html>` tags in the iframe element. After deleting it through the console, the page becomes interactable again

![image](https://user-images.githubusercontent.com/52806204/155458465-6e79321f-e99b-4174-a161-d71c0a95930a.png)

![image](https://user-images.githubusercontent.com/52806204/155459148-928b86a7-d490-4616-8600-0a144ce8c059.png)

After deleting the iframe element:
![image](https://user-images.githubusercontent.com/52806204/155459614-9e88e0dc-a180-46db-b0ec-ad9a547dab50.png)

**Comment by Digs01** [comment] 2022-02-25 09:49
I was having the same problem and getting the bugs as outlined in an earlier posted issue (#121). I used the yarn format command and it seems to have done the trick

**Comment by daniel-makarov** [comment] 2022-02-27 01:20
Try running "yarn start"

**Comment by Louanes1** [comment] 2022-02-27 17:40
I am facing same issue, even when I use "yarn start" the front page of my localhost is still not clickable. It becomes clickable when I delete the Iframe from the console directly as @mubarakone suggested, but then the authentication is failling  and I guess pretty much everything else will not work as expected ..

**Comment by Y0moo** [comment] 2022-02-27 20:19
Please share the console log. Do you mean it stops be clickable after you edit the code?

**Comment by john-petcoin** [comment] 2022-02-27 22:57
I also have the same issue. Removing the iframe indeed fixes the issue. I'm not sure of the cause though..
![Screenshot 2022-02-27 175632](https://user-images.githubusercontent.com/98372884/155903513-58e79c4b-0d01-4d89-b998-4ba7f8e95e59.png)

**Comment by freaker10k** [comment] 2022-02-28 02:17
I have the same issue
"yarn format" fixed it on launch, however
the interface locked up again after sending some test funds on the wallet page.
I need to keep refreshing to unlock the interface.

**Comment by Y0moo** [comment] 2022-08-26 06:02
Closing since we released V2

**Closed by Y0moo** 2022-08-26 06:02 UTC
