### ISSUE TITLE
Yarn Install Error

### ISSUE THREAD

**Issue by 3web3** [ethereum-boilerplate/ethereum-boilerplate#138] opened 2022-03-21 19:35 UTC
I am getting this error on installation. I have searched many issues on the internet but could not solve it. Any idea?

<img width="563" alt="Ekran Resmi 2022-03-21 22 27 43" src="https://user-images.githubusercontent.com/29187529/159350164-a740c1a2-a8c7-4b93-92ce-3faaa220aed3.png">

**Comment by Nexidian** [comment] 2022-03-21 21:44
Hey @7777nft 

Could you please run `yarn install` from the root directory of this project before running `yarn start`. 

From the look of your screenshot it doesn't look like you've installed the dependencies yet

**Comment by 7777nft** [comment] 2022-03-22 03:39
@Nexidian I had done this. I couldn't understand what is the problem.

<img width="1042" alt="Ekran Resmi 2022-03-22 06 37 27" src="https://user-images.githubusercontent.com/29187529/159403106-bb63f203-a131-4a6e-bcb0-adefbd2782da.png">

I also try with npm but I get an error.

`mbonft@192 ethereum-boilerplate-main % npm run start

> ethereum-boilerplate@0.1.0 start
> set "GENERATE_SOURCEMAP=false" && react-app-rewired start

sh: react-app-rewired: command not found
mbonft@192 ethereum-boilerplate-main % `

**Comment by Nexidian** [comment] 2022-03-22 08:55
@7777nft The error is mentioned in the yarn output there. You look to be missing the Xcode CommandLineTools needed for MacOS. The command `yarn start` is failing still because `yarn install` failed.


- Install the Xcode dev libraries with `sudo xcode-select --install`
- Remove `package-lock.json` as this is from your NPM command and is not used here
- Rerun `yarn install`


This should resolve your problem

**Comment by 7777nft** [comment] 2022-03-22 14:21
@Nexidian Thank you so much. This solved my problem. However, I got the error here #135. And I couldn't understand your solution here #139. What do I need to change?

**Comment by LJ-Rawnet** [comment] 2022-03-22 15:26
@7777nft You've only taken part of my solution. 

Move the options initialisation on line 96 in your screenshot and place it above the for loop. 

It should look like this

```js
const options = {
    contractAddress,
    functionName: name,
    abi: contract?.abi,
    params,
};

let isView = false;
for (let method of options.abi) {
    if (method.name !== name) continue;
    console.log(method);
    if (method.stateMutability === "view") isView = true;
}
```

**Comment by LJ-Rawnet** [comment] 2022-03-22 15:28
As for the `source map` issue you can ignore those. They are caused by a configuration issue between webpack5 and walletconnect.

The site will function with those errors. I will get a PR to resolve it soon

**Comment by 7777nft** [comment] 2022-03-22 15:43
@Nexidian @LJ-Rawnet Thanks for your wonderful support. These answers will help those who have the same problem.

**Comment by Nexidian** [comment] 2022-03-22 15:50
@7777nft  Glad to help buddy. 


Just FYI I am also @LJ-Rawnet - Forgot I was logged into my work account :)

**Comment by sergism77** [comment] 2022-03-29 11:50
> @7777nft You've only taken part of my solution.
> 
> Move the options initialisation on line 96 in your screenshot and place it above the for loop.
> 
> It should look like this
> 
> ```js
> const options = {
>     contractAddress,
>     functionName: name,
>     abi: contract?.abi,
>     params,
> };
> 
> let isView = false;
> for (let method of options.abi) {
>     if (method.name !== name) continue;
>     console.log(method);
>     if (method.stateMutability === "view") isView = true;
> }
> ```

I tried this, but still getting error. Any ideas?
![Skjermbilde 2022-03-29 kl  13 49 23](https://user-images.githubusercontent.com/97520112/160604888-88a4a035-8781-4374-83b2-8f930189258f.png)

**Comment by Nexidian** [comment] 2022-03-29 11:54
@sergism77 You've also only taken part of my solution. 

You need to update your line 97 to be

```js
for (let method of options.abi) {
```

We have moved the options section above the for loop so we can make use of `options.abi` which we can safely assume will either be populated or `undefined`, if its `undefined` the loop will just not run. 

This prevents the use of unsafe optional chaining

**Comment by sergism77** [comment] 2022-03-29 11:56
> @sergism77 You've also only taken part of my solution.
> 
> You need to update your line 97 to be
> 
> ```js
> for (let method of options.abi) {
> ```
> 
> We have moved the options section above the for loop so we can make use of `options.abi` which we can safely assume will either be populated or `undefined`, if its `undefined` the loop will just not run.
> 
> This prevents the use of unsafe optional chaining

Thank you! :) got code blind...

**Comment by CryptoWizard2011** [comment] 2022-03-30 19:29
i get the below error trying to install yarn?

error An unexpected error occurred: "Commit hash required".

**Comment by LJ-Rawnet** [comment] 2022-03-31 08:33
@CryptoWizard2011  This usually happens when you have run `npm install` within a yarn project. Remove any `package-lock.json` and `yarn.lock` and run `yarn install` again.

@7777nft If your original issue has been resolved would you minding closing this ticket please

**Comment by CryptoWizard2011** [comment] 2022-04-01 09:13
> 

i seem to have this working on home pc but my work laptop will not install yarn 1.22.18 but only install .15 gone through all the roots i'm i missing something , i want to be able to carry on while at work with the project

**Comment by Y0moo** [comment] 2022-08-26 06:01
Closing since we released V2

**Closed by Y0moo** 2022-08-26 06:01 UTC
